---
title: "Activity monitoring data analysis "
author: "Haftom"
date: "September 22, 2018"
output: html_document
---



Loading required packages 
---------------------------
```{r}
setwd("C:/Users/Haftom/ProgrammingAssignment2")
library(knitr)
library(dplyr)
require(ggplot2)
```
Reading Data set
-------------------------
```{r}
readData<-function()
{
  df<-read.csv("activity.csv",header=T,sep=",",colClass=c("numeric","Date","numeric"))
  #df[complete.cases(df),]
}
##head
head(readData())
##tail
tail(readData())
#summary
summary(readData())
```

Histogram of the total number of steps taken each day
-------------------------------------------------------


```{r pressure, echo=TRUE}
steps_hist_stat<-function(data){
  #summarizing data by day
  
  daily<-summarise(group_by(data,date),
                   total_steps=sum(steps))
  
  #ploting steps
  with(daily,hist(total_steps, main="Total number of steps per day", 
                  xlab="steps/Day",col="light blue"))
  
  #Mean and median number of steps taken each day
  print("Mean and median number of steps taken each day")
  summary(daily$total_steps)
}
steps_hist_stat(readData())
```

Time series plot of the average number of steps taken
-------------------------------------------------------------

```{r}
steps_by_interval<-function(data,title)
{
  #Aggrigating and ploting by intervals
  df<-aggregate(steps ~ interval,data, mean)
  with ( df, 
         #plot
         plot(steps ~ interval,type='l',
              main="Time series plot of the average number of steps taken",
              xlab="Interval")
         
  )
  #max intrval
  print("Max average step by 5 min Interval")
  df[which.max(df$steps),]
  
  
}
steps_by_interval(readData())

```


NA investigation
----------------------
```{r}
sum(is.na(readData()))

## NA's by variables
sapply(readData(), function(x){sum(is.na(x))})



```

##strategy for imputing missing data

I used  mean imputation method to replace NA's.

Replaceing mean value for each interval.

```{r}
clean_data<-function(data)
{
  df<-aggregate(steps ~ interval,data, mean)
  for (i in 1:nrow(data)) {
    if (is.na(data$steps[i])) {
      intervalv <- data$interval[i]
      stepsv <- df[df$interval == intervalv,]
      data$steps[i] <- stepsv$steps
    }
  }
  print("check if there are anymore NA's")
  print(table(is.na(data)))
  data
}

```
Histogram of the total number of steps taken each day after missing values are imputed
------------------------------------------------------------------------------------------
```{r}
data<-clean_data(readData())
steps_hist_stat(data)

```
comparing the average number of steps taken per 5-minute interval across weekdays and weekends
--------------------------------------------------------------------------------------------------
```{r}
data$weekpart<-weekdays(as.Date(data$date))
data$weekpart[data$weekpart %in% c('Saturday','Sunday')]<-'weekend'
data$weekpart[data$weekpart %in% c('Monday','Tuesday','Wednesday','Thursday','Friday')]<-'weekdays'
step_data<-aggregate(steps ~ interval+weekpart,data, mean)

p<-ggplot(step_data,aes(interval,steps))
p+geom_line()+facet_wrap(~weekpart,ncol=1)


  




```







